apiVersion: v2
name: radarr
description: Smart PVR for newsgroup and bittorrent users
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/radarr
icon: https://github.com/Radarr/Radarr/blob/aphrodite/Logo/512.png?raw=true
sources:
  - https://github.com/Radarr/Radarr
  - https://github.com/k8s-at-home/container-images
dependencies:
  - name: radarr
    repository: https://k8s-at-home.com/charts/
    version: 16.3.2

type: application

# Note: k8s-at-home repository is no longer maintained
version: "16.3.2"

# renovate: datasource=github-releases depName=Radarr/Radarr
appVersion: "v5.18.4.9674"

keywords:
  - radarr
  - torrent
  - usenet
